### ISSUE TITLE
Investigate BGEN reader in PySnpTools

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit-bgen#3]
More details at https://github.com/limix/bgen-reader-py/issues/30#issuecomment-663164596

**Comment by eric-czech** [comment]
Since it is ultimately the same code being used under the hood, I think it probably makes sense to target @horta's [cbgen-py](https://github.com/limix/cbgen-py/tree/master/cbgen) project instead.  The lighter dependencies it has would be a nice benefit too.

He describes some of the remaining overhead in sequential bulk access here: https://github.com/limix/bgen-reader-py/issues/30#issuecomment-675659810.

**Comment by horta** [comment]
Released new version of cbgen with documentation: https://github.com/limix/cbgen
Looks like very ready to use. It makes uses of the latest bgen C library with additional error checkings.
